#!/bin/zsh


bfile=$HOME/.config/bookmarks/local-bookmarks.txt

afile=$HOME/.config/bookmarks/baliases.sh

case $1 in
    "list")
        echo "NAME - PATH" ; echo "-----------------------------" ; cat $bfile ; exit 0
        ;;
    "edit")
        $EDITOR $bfile
        bmark update_aliases
        exit 0
        ;;
    "rm")
        line=$(grep "^$2 - " $bfile) || eval 'echo "no bookmark named \"$2\"" ; exit 1'
        echo "$line"
        echo $(cat $bfile | sed "/$line/d" )
        bmark update_aliases
        exit 0
        ;;
    "update_aliases")
        echo "# Autogenerated aliases for bookmarked places" > $afile
        cat $bfile | awk -F ' - ' '{print "alias _\"" $1 "\"=\"cd " $2"\""}' >> $afile
        echo "updated bookmark aliases."
        exit 0
        ;;
    "add")
        [[ "$2" = "" ]] && echo "please give bookmark a name" && exit 1
        bmark="$2 - $(pwd)"
        echo "$bmark" >> $bfile && echo "Created bookmark: $bmark"
        bmark update_aliases
        ;;
    *)
        echo "bmark options are: add, list, edit, rm and update_aliases" && exit 0
esac
